#BACKGROUNDS
image Heartslabyul_BG_DAY = im.Scale("Backgrounds/Background_Heartslabyul_Dorm.png", 1920,1080)
image Home_Night = im.Scale("Backgrounds/Home_Night.jpg", 1920, 1080)
image Bus_Home = im.Scale("Backgrounds/Bus_Home.jpg", 1920, 1080)
image Old_School = im.Scale("Backgrounds/Old_School.jpg", 1920, 1080)
image Room_Night = im.Scale("Backgrounds/Room_Night.jpg", 1920, 1080)
image Night_Kitchen = im.Scale("Backgrounds/Night_Kitchen.jpg", 1920, 1080)
image empty = im.Scale("Backgrounds/empty.png", 1920, 1080)
image Mirror_Chamber = im.Scale("Backgrounds/Mirror_Chamber.png", 1920, 1080)


#ELIZABETH
    #DORM UNIFORM
        #HANDSUP
image Liz_Idle_DormU_HU_Angry_combi = "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Angry_combi.png"
image Liz_Idle_DormU_HU_Angry_heart = "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Angry_heart.png"
image Liz_Idle_DormU_HU_Sad_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Sad_combi.png"
image Liz_Idle_DormU_HU_Sad_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Sad_heart.png"
image Liz_Idle_DormU_HU_Screaming_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Screaming_combi.png"
image Liz_Idle_DormU_HU_Screaming_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Screaming_heart.png"
image Liz_Idle_DormU_HU_SmileCB_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_SmileCB_combi.png"
image Liz_Idle_DormU_HU_SmileCB_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_SmileCB_heart.png"
image Liz_Idle_DormU_HU_SmileCEOM_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_SmileCEOM_combi.png"
image Liz_Idle_DormU_HU_SmileCEOM_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_SmileCEOM_heart.png"
image Liz_Idle_DormU_HU_SmileOB_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_SmileOB_combi.png"
image Liz_Idle_DormU_HU_SmileOB_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_SmileOB_heart.png"
image Liz_Idle_DormU_HU_SmileOECM_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_SmileOECM_combi.png"
image Liz_Idle_DormU_HU_SmileOECM_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_SmileOECM_heart.png"
image Liz_Idle_DormU_HU_Tears_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Tears_combi.png"
image Liz_Idle_DormU_HU_Tears_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Tears_heart.png"
image Liz_Idle_DormU_HU_Weeping_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Weeping_combi.png"
image Liz_Idle_DormU_HU_Weeping_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Weeping_heart.png"
image Liz_Idle_DormU_HU_Winkom_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Winkom_combi.png"
image Liz_Idle_DormU_HU_Winkom_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Winkom_heart.png"
image Liz_Idle_DormU_HU_Winkuwu_combi =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Winkuwu_combi.png"
image Liz_Idle_DormU_HU_Winkuwu_heart =  "Characters/Elizabeth/Idle/Hand up/DORM UNIFORM HU/Liz_Idle_DormU_HU_Winkuwu_heart.png"
        #HANDSDOWN
image Liz_Idle_DormU_HD_Angry_combi = "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Angry_combi.png"
image Liz_Idle_DormU_HD_Angry_heart = "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Angry_heart.png"
image Liz_Idle_DormU_HD_Sad_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Sad_combi.png"
image Liz_Idle_DormU_HD_Sad_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Sad_heart.png"
image Liz_Idle_DormU_HD_Screaming_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Screaming_combi.png"
image Liz_Idle_DormU_HD_Screaming_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Screaming_heart.png"
image Liz_Idle_DormU_HD_SmileCB_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_SmileCB_combi.png"
image Liz_Idle_DormU_HD_SmileCB_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_SmileCB_heart.png"
image Liz_Idle_DormU_HD_SmileCEOM_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_SmileCEOM_combi.png"
image Liz_Idle_DormU_HD_SmileCEOM_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_SmileCEOM_heart.png"
image Liz_Idle_DormU_HD_SmileOB_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_SmileOB_combi.png"
image Liz_Idle_DormU_HD_SmileOB_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_SmileOB_heart.png"
image Liz_Idle_DormU_HD_SmileOECM_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_SmileOECM_combi.png"
image Liz_Idle_DormU_HD_SmileOECM_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_SmileOECM_heart.png"
image Liz_Idle_DormU_HD_Tears_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Tears_combi.png"
image Liz_Idle_DormU_HD_Tears_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Tears_heart.png"
image Liz_Idle_DormU_HD_Weeping_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Weeping_combi.png"
image Liz_Idle_DormU_HD_Weeping_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Weeping_heart.png"
image Liz_Idle_DormU_HD_Winkom_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Winkom_combi.png"
image Liz_Idle_DormU_HD_Winkom_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Winkom_heart.png"
image Liz_Idle_DormU_HD_Winkuwu_combi =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Winkuwu_combi.png"
image Liz_Idle_DormU_HD_Winkuwu_heart =  "Characters/Elizabeth/Idle/Hand Down/DORM UNIFORM HD/Liz_Idle_DormU_HD_Winkuwu_heart.png"

    #SCHOOLUNIFORM
        #HANDSUP
image Liz_Idle_SchoolU_HU_Angry_combi = "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Angry_combi.png"
image Liz_Idle_SchoolU_HU_Angry_heart = "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Angry_heart.png"
image Liz_Idle_SchoolU_HU_Sad_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Sad_combi.png"
image Liz_Idle_SchoolU_HU_Sad_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Sad_heart.png"
image Liz_Idle_SchoolU_HU_Screaming_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Screaming_combi.png"
image Liz_Idle_SchoolU_HU_Screaming_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Screaming_heart.png"
image Liz_Idle_SchoolU_HU_SmileCB_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_SmileCB_combi.png"
image Liz_Idle_SchoolU_HU_SmileCB_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_SmileCB_heart.png"
image Liz_Idle_SchoolU_HU_SmileCEOM_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_SmileCEOM_combi.png"
image Liz_Idle_SchoolU_HU_SmileCEOM_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_SmileCEOM_heart.png"
image Liz_Idle_SchoolU_HU_SmileOB_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_SmileOB_combi.png"
image Liz_Idle_SchoolU_HU_SmileOB_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_SmileOB_heart.png"
image Liz_Idle_SchoolU_HU_SmileOECM_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_SmileOECM_combi.png"
image Liz_Idle_SchoolU_HU_SmileOECM_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_SmileOECM_heart.png"
image Liz_Idle_SchoolU_HU_Tears_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Tears_combi.png"
image Liz_Idle_SchoolU_HU_Tears_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Tears_heart.png"
image Liz_Idle_SchoolU_HU_Weeping_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Weeping_combi.png"
image Liz_Idle_SchoolU_HU_Weeping_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Weeping_heart.png"
image Liz_Idle_SchoolU_HU_Winkom_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Winkom_combi.png"
image Liz_Idle_SchoolU_HU_Winkom_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Winkom_heart.png"
image Liz_Idle_SchoolU_HU_Winkuwu_combi =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Winkuwu_combi.png"
image Liz_Idle_SchoolU_HU_Winkuwu_heart =  "Characters/Elizabeth/Idle/Hand up/SCHOOL UNIFORM HU/Liz_Idle_SchoolU_HU_Winkuwu_heart.png"
        #HANDSDOWN
image Liz_Idle_SchoolU_HD_Angry_combi = "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Angry_combi.png"
image Liz_Idle_SchoolU_HD_Angry_heart = "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Angry_heart.png"
image Liz_Idle_SchoolU_HD_Sad_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Sad_combi.png"
image Liz_Idle_SchoolU_HD_Sad_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Sad_heart.png"
image Liz_Idle_SchoolU_HD_Screaming_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Screaming_combi.png"
image Liz_Idle_SchoolU_HD_Screaming_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Screaming_heart.png"
image Liz_Idle_SchoolU_HD_SmileCB_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_SmileCB_combi.png"
image Liz_Idle_SchoolU_HD_SmileCB_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_SmileCB_heart.png"
image Liz_Idle_SchoolU_HD_SmileCEOM_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_SmileCEOM_combi.png"
image Liz_Idle_SchoolU_HD_SmileCEOM_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_SmileCEOM_heart.png"
image Liz_Idle_SchoolU_HD_SmileOB_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_SmileOB_combi.png"
image Liz_Idle_SchoolU_HD_SmileOB_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_SmileOB_heart.png"
image Liz_Idle_SchoolU_HD_SmileOECM_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_SmileOECM_combi.png"
image Liz_Idle_SchoolU_HD_SmileOECM_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_SmileOECM_heart.png"
image Liz_Idle_SchoolU_HD_Tears_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Tears_combi.png"
image Liz_Idle_SchoolU_HD_Tears_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Tears_heart.png"
image Liz_Idle_SchoolU_HD_Weeping_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Weeping_combi.png"
image Liz_Idle_SchoolU_HD_Weeping_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Weeping_heart.png"
image Liz_Idle_SchoolU_HD_Winkom_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Winkom_combi.png"
image Liz_Idle_SchoolU_HD_Winkom_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Winkom_heart.png"
image Liz_Idle_SchoolU_HD_Winkuwu_combi =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Winkuwu_combi.png"
image Liz_Idle_SchoolU_HD_Winkuwu_heart =  "Characters/Elizabeth/Idle/Hand Down/SCHOOL UNIFORM HD/Liz_Idle_SchoolU_HD_Winkuwu_heart.png"

    #PAJAMAS
        #HANDSUP
image Liz_Idle_Pajamas_HU_Angry_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Angry_glasses.png"
image Liz_Idle_Pajamas_HU_Angry_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Angry_raw.png"
image Liz_Idle_Pajamas_HU_Crying_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Crying_glasses.png"
image Liz_Idle_Pajamas_HU_Crying_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Crying_raw.png"
image Liz_Idle_Pajamas_HU_Sad_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Sad_glasses.png"
image Liz_Idle_Pajamas_HU_Sad_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Sad_raw.png"
image Liz_Idle_Pajamas_HU_Screaming_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Screaming_glasses.png"
image Liz_Idle_Pajamas_HU_Screaming_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Screaming_raw.png"
image Liz_Idle_Pajamas_HU_SmileCB_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_SmileCB_glasses.png"
image Liz_Idle_Pajamas_HU_SmileCB_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_SmileCB_raw.png"
image Liz_Idle_Pajamas_HU_SmileCEOM_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_SmileCEOM_glasses.png"
image Liz_Idle_Pajamas_HU_SmileCEOM_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_SmileCEOM_raw.png"
image Liz_Idle_Pajamas_HU_SmileOB_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_SmileOB_glasses.png"
image Liz_Idle_Pajamas_HU_SmileOB_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_SmileOB_raw.png"
image Liz_Idle_Pajamas_HU_SmileOECM_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_SmileOECM_glasses.png"
image Liz_Idle_Pajamas_HU_SmileOECM_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_SmileOECM_raw.png"
image Liz_Idle_Pajamas_HU_Tears_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Tears_glasses.png"
image Liz_Idle_Pajamas_HU_Tears_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Tears_raw.png"
image Liz_Idle_Pajamas_HU_Winkom_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Winkom_glasses.png"
image Liz_Idle_Pajamas_HU_Winkom_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Winkom_raw.png"
image Liz_Idle_Pajamas_HU_Winkuwu_glasses = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Winkuwu_glasses.png"
image Liz_Idle_Pajamas_HU_Winkuwu_raw = "Characters/Elizabeth/Idle/Hand up/PAJAMAS HU/Liz_Idle_Pajamas_HU_Winkuwu_raw.png"
        #HANDSDOWN
image Liz_Idle_Pajamas_HD_Angry_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Angry_glasses.png"
image Liz_Idle_Pajamas_HD_Angry_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Angry_raw.png"
image Liz_Idle_Pajamas_HD_Crying_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Crying_glasses.png"
image Liz_Idle_Pajamas_HD_Crying_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Crying_raw.png"
image Liz_Idle_Pajamas_HD_Sad_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Sad_glasses.png"
image Liz_Idle_Pajamas_HD_Sad_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Sad_raw.png"
image Liz_Idle_Pajamas_HD_Screaming_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Screaming_glasses.png"
image Liz_Idle_Pajamas_HD_Screaming_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Screaming_raw.png"
image Liz_Idle_Pajamas_HD_SmileCB_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_SmileCB_glasses.png"
image Liz_Idle_Pajamas_HD_SmileCB_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_SmileCB_raw.png"
image Liz_Idle_Pajamas_HD_SmileCEOM_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_SmileCEOM_glasses.png"
image Liz_Idle_Pajamas_HD_SmileCEOM_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_SmileCEOM_raw.png"
image Liz_Idle_Pajamas_HD_SmileOB_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_SmileOB_glasses.png"
image Liz_Idle_Pajamas_HD_SmileOB_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_SmileOB_raw.png"
image Liz_Idle_Pajamas_HD_SmileOECM_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_SmileOECM_glasses.png"
image Liz_Idle_Pajamas_HD_SmileOECM_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_SmileOECM_raw.png"
image Liz_Idle_Pajamas_HD_Tears_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Tears_glasses.png"
image Liz_Idle_Pajamas_HD_Tears_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Tears_raw.png"
image Liz_Idle_Pajamas_HD_Winkom_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Winkom_glasses.png"
image Liz_Idle_Pajamas_HD_Winkom_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Winkom_raw.png"
image Liz_Idle_Pajamas_HD_Winkuwu_glasses = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Winkuwu_glasses.png"
image Liz_Idle_Pajamas_HD_Winkuwu_raw = "Characters/Elizabeth/Idle/Hand Down/PAJAMAS HD/Liz_Idle_Pajamas_HD_Winkuwu_raw.png"

    #BIKINI
        #HANDSUP
image Liz_Idle_Bikini_HU_Angry_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Angry_glasses.png"
image Liz_Idle_Bikini_HU_Angry_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Angry_raw.png"
image Liz_Idle_Bikini_HU_Sad_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Sad_glasses.png"
image Liz_Idle_Bikini_HU_Sad_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Sad_raw.png"
image Liz_Idle_Bikini_HU_Screaming_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Screaming_glasses.png"
image Liz_Idle_Bikini_HU_Screaming_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Screaming_raw.png"
image Liz_Idle_Bikini_HU_SmileCB_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_SmileCB_glasses.png"
image Liz_Idle_Bikini_HU_SmileCB_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_SmileCB_raw.png"
image Liz_Idle_Bikini_HU_SmileCEOM_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_SmileCEOM_glasses.png"
image Liz_Idle_Bikini_HU_SmileCEOM_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_SmileCEOM_raw.png"
image Liz_Idle_Bikini_HU_SmileOB_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_SmileOB_glasses.png"
image Liz_Idle_Bikini_HU_SmileOB_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_SmileOB_raw.png"
image Liz_Idle_Bikini_HU_SmileOECM_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_SmileOECM_glasses.png"
image Liz_Idle_Bikini_HU_SmileOECM_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_SmileOECM_raw.png"
image Liz_Idle_Bikini_HU_Tears_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Tears_glasses.png"
image Liz_Idle_Bikini_HU_Tears_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Tears_raw.png"
image Liz_Idle_Bikini_HU_Weeping_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Weeping_glasses.png"
image Liz_Idle_Bikini_HU_Weeping_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Weeping_raw.png"
image Liz_Idle_Bikini_HU_Winkom_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Winkom_glasses.png"
image Liz_Idle_Bikini_HU_Winkom_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Winkom_raw.png"
image Liz_Idle_Bikini_HU_Winkuwu_glasses = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Winkuwu_glasses.png"
image Liz_Idle_Bikini_HU_Winkuwu_raw = "Characters/Elizabeth/Idle/Hand up/BIKINI HU/Liz_Idle_Bikini_HU_Winkuwu_raw.png"
        #HANDSDOWN
image Liz_Idle_Bikini_HD_Angry_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Angry_glasses.png"
image Liz_Idle_Bikini_HD_Angry_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Angry_raw.png"
image Liz_Idle_Bikini_HD_Sad_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Sad_glasses.png"
image Liz_Idle_Bikini_HD_Sad_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Sad_raw.png"
image Liz_Idle_Bikini_HD_Screaming_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Screaming_glasses.png"
image Liz_Idle_Bikini_HD_Screaming_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Screaming_raw.png"
image Liz_Idle_Bikini_HD_SmileCB_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_SmileCB_glasses.png"
image Liz_Idle_Bikini_HD_SmileCB_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_SmileCB_raw.png"
image Liz_Idle_Bikini_HD_SmileCEOM_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_SmileCEOM_glasses.png"
image Liz_Idle_Bikini_HD_SmileCEOM_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_SmileCEOM_raw.png"
image Liz_Idle_Bikini_HD_SmileOB_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_SmileOB_glasses.png"
image Liz_Idle_Bikini_HD_SmileOB_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_SmileOB_raw.png"
image Liz_Idle_Bikini_HD_SmileOECM_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_SmileOECM_glasses.png"
image Liz_Idle_Bikini_HD_SmileOECM_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_SmileOECM_raw.png"
image Liz_Idle_Bikini_HD_Tears_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Tears_glasses.png"
image Liz_Idle_Bikini_HD_Tears_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Tears_raw.png"
image Liz_Idle_Bikini_HD_Weeping_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Weeping_glasses.png"
image Liz_Idle_Bikini_HD_Weeping_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Weeping_raw.png"
image Liz_Idle_Bikini_HD_Winkom_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Winkom_glasses.png"
image Liz_Idle_Bikini_HD_Winkom_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Winkom_raw.png"
image Liz_Idle_Bikini_HD_Winkuwu_glasses = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Winkuwu_glasses.png"
image Liz_Idle_Bikini_HD_Winkuwu_raw = "Characters/Elizabeth/Idle/Hand Down/BIKINI HD/Liz_Idle_Bikini_HD_Winkuwu_raw.png"












